services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  postgres_data:
